apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: simple-go-k8s
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    tier: backend
  type: ClusterIP
status:
  loadBalancer: {}
