apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: simple-go-k8s
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    tier: db
  type: ClusterIP
status:
  loadBalancer: {}
