apiVersion: v1
kind: Service
metadata:
  name: nginx-service-node-port
spec:
  # Used for expose the port to out side world
  # Accessible from outside
  # The exposed port will be declared by `nodePort`
  type: NodePort
  selector:
      type: gw
  ports:
    # Service port will listen
  - port: 80
    # Pod port will expose
    targetPort: 80
    # Port the service will
    # nodePort: 
