apiVersion: v1
kind: Service
metadata:
  name: nginx-service-cluster-ip
spec:
  # Default option
  # By declaring this type, all selector pods will have a cluster IP
  # Only accessible within the cluster
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    type: gw