apiVersion: v1
kind: Service
metadata:
  name: nginx-service-load-balancer
spec:
  # In local env, LoadBalancer behaves like NodePort with additional feature like load balancing
  # Accessible from outside. Automatically creates clusterIP & NodePort
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    type: gw