apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replicationcontroller
  labels:
    type: replication 
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        type: gw
    spec:
      containers:
      - name: nginx-container
        image: nginx  
  replicas: 3
